/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informationSystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author castillo
 */
public class changeaccountadmin extends javax.swing.JFrame {

    DBconnetion mycon = new DBconnetion();
    Connection conn;
    PreparedStatement pstmt;
    Statement stmt;
    ResultSet rs;
    String employeeid;
    
    
    
    /**
     * Creates new form changeaccountadmin
     */
    public changeaccountadmin() {
        initComponents();
        mycon.doConnect();
        center();
        admintable();
        
    }
    
             void center(){

    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize() ;
    Dimension jscreen = this.getSize();

    this.setLocation((screen.width - jscreen.width)/2, ((screen.height-jscreen.height)/2)-90);

    } 
                 public void close(){
    WindowEvent winclose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
}
                 
                 void admintable(){
                     try {
                         conn = mycon.con;
                         stmt = conn.createStatement();
                         rs = stmt.executeQuery("select * from admin");
                         DefaultTableModel model = ((DefaultTableModel)tbladmin.getModel());
                         model.getDataVector().removeAllElements();
                         
                         while(rs.next()){
                             model.addRow(new Object[]{rs.getString(8),rs.getString(1),rs.getString(2), rs.getString(3),rs.getString(4)});
                         }
                     } catch (Exception e) {
                     }
                 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpassword = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        txtmiddlename = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtemployeeid = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbgender = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbladmin = new javax.swing.JTable();
        lblemployeeid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);
        jPanel1.add(txtpassword);
        txtpassword.setBounds(210, 440, 370, 30);
        jPanel1.add(txtfirstname);
        txtfirstname.setBounds(220, 140, 390, 30);
        jPanel1.add(txtmiddlename);
        txtmiddlename.setBounds(220, 180, 390, 30);
        jPanel1.add(txtlastname);
        txtlastname.setBounds(220, 220, 390, 30);

        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtageKeyTyped(evt);
            }
        });
        jPanel1.add(txtage);
        txtage.setBounds(220, 260, 390, 30);
        jPanel1.add(txtaddress);
        txtaddress.setBounds(220, 300, 390, 30);
        jPanel1.add(txtemployeeid);
        txtemployeeid.setBounds(170, 510, 280, 30);
        jPanel1.add(txtusername);
        txtusername.setBounds(210, 400, 370, 30);

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch);
        txtsearch.setBounds(160, 100, 320, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchicon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 100, 30, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admineditaccountsavebutton.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 100, 100, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backicon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(460, 500, 50, 50);

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(cbgender);
        cbgender.setBounds(220, 340, 390, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clearicon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 100, 60, 30);

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(520, 510, 90, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("Search");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 100, 90, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admineditaccountwallpaper.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 568);

        tbladmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Firstname", "Middlename", "Lastname", "Username"
            }
        ));
        tbladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbladminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbladmin);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 570, 630, 90);
        jPanel1.add(lblemployeeid);
        lblemployeeid.setBounds(180, 140, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        settings adminsettings = new settings();
        adminsettings.setVisible(true);
        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conn = mycon.con;
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select * from admin where firstname like'" + txtsearch.getText().toUpperCase() + "%' or middlename like'" + txtsearch.getText().toUpperCase() + "%' or lastname like'" + txtsearch.getText().toUpperCase() + "%'");
            
            while(rs.next()){
                txtfirstname.setText(rs.getString(1));
                txtmiddlename.setText(rs.getString(2));
                txtlastname.setText(rs.getString(3));
                txtage.setText(rs.getString(4));
                txtaddress.setText(rs.getString(5));
                txtusername.setText(rs.getString(6));
                txtpassword.setText(rs.getString(7));
                txtemployeeid.setText(rs.getString(8));
                String comboboxgender = rs.getString(9);
                String comboboxadmingender = "MALE";
                
                if(comboboxgender == comboboxadmingender){
                    cbgender.setSelectedIndex(0);
                }else{
                    cbgender.setSelectedIndex(1);
                }
                
                
                
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyTyped
        char savebutton = evt.getKeyChar();
        if(!(Character.isDigit(savebutton)) || (savebutton == KeyEvent.VK_BACK_SPACE) || (savebutton == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtageKeyTyped

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
            conn = mycon.con;
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select * from admin where firstname like'" + txtsearch.getText().toUpperCase() + "%' or middlename like'" + txtsearch.getText().toUpperCase() + "%' or lastname like'" + txtsearch.getText().toUpperCase() + "%' or employeeid like'" + txtsearch.getText().toUpperCase() + "'");
            
            while(rs.next()){
                txtfirstname.setText(rs.getString(1));
                txtmiddlename.setText(rs.getString(2));
                txtlastname.setText(rs.getString(3));
                txtage.setText(rs.getString(4));
                txtaddress.setText(rs.getString(5));
                txtusername.setText(rs.getString(6));
                txtpassword.setText(rs.getString(7));
                txtemployeeid.setText(rs.getString(8));
                lblemployeeid.setText(rs.getString(1));
                String comboboxgender = rs.getString(9);
                String comboboxadmingender = "MALE";
                
                if(comboboxgender == comboboxadmingender){
                    cbgender.setSelectedIndex(0);
                }else{
                    cbgender.setSelectedIndex(1);
                }
                
                
                
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
            
    }//GEN-LAST:event_txtsearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int ask = JOptionPane.showConfirmDialog(this, "Do you want to update this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(ask == JOptionPane.YES_NO_OPTION){
            try {
                conn = mycon.con;
                String query = "update admin set firstname=?, middlename=?, lastname=?, age=?, address=?, username=?, password=?, employeeid=?, gender=? where employeeid=?";
                pstmt = conn.prepareStatement(query);
                pstmt.setString(1, txtfirstname.getText().toUpperCase());
                pstmt.setString(2, txtmiddlename.getText().toUpperCase());
                pstmt.setString(3, txtlastname.getText().toUpperCase());
                pstmt.setInt(4, Integer.parseInt(txtage.getText()));
                pstmt.setString(5, txtaddress.getText().toUpperCase());
                pstmt.setString(6, txtusername.getText().toUpperCase());
                pstmt.setString(7, txtpassword.getText().toUpperCase());
                pstmt.setString(8, txtemployeeid.getText().toUpperCase());
                pstmt.setString(9, cbgender.getSelectedItem().toString().toUpperCase());
                pstmt.setString(10, lblemployeeid.getText().toUpperCase());
                pstmt.execute();
                
                JOptionPane.showMessageDialog(this, "Data has been updated");
                admintable();
                txtfirstname.setText(null);
                txtmiddlename.setText(null);
                txtlastname.setText(null);
                txtage.setText(null);
                txtaddress.setText(null);
                txtusername.setText(null);
                txtpassword.setText(null);
                txtemployeeid.setText(null);
                cbgender.setSelectedIndex(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtsearch.setText(null);
        txtfirstname.setText(null);
        txtmiddlename.setText(null);
        txtlastname.setText(null);
        txtemployeeid.setText(null);
        txtage.setText(null);
        txtaddress.setText(null);
        cbgender.setSelectedIndex(0);
        txtusername.setText(null);
        txtpassword.setText(null);
        admintable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbladminMouseClicked
        try {
            int adminrow = tbladmin.getSelectedRow();
            
            String adminrow1 = (tbladmin.getModel().getValueAt(adminrow, 0).toString());
            
            conn = mycon.con;
            String query = "select * from admin where employeeid='" + adminrow1 + "'";
            pstmt = conn.prepareStatement(query);
            rs = pstmt.executeQuery();
            
            while(rs.next()){
                txtfirstname.setText(rs.getString(1));
                txtmiddlename.setText(rs.getString(2));
                txtlastname.setText(rs.getString(3));
                txtage.setText(rs.getString(4));
                txtaddress.setText(rs.getString(5));
                txtusername.setText(rs.getString(6));
                txtpassword.setText(rs.getString(7));
                txtemployeeid.setText(rs.getString(8));
                cbgender.setSelectedItem(rs.getString(9));
                employeeid = rs.getString(8);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_tbladminMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int askdelete = JOptionPane.showConfirmDialog(this, "Do you want to delete this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(askdelete == JOptionPane.YES_OPTION){
            if(txtemployeeid.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please select the data first");
            }else{
                try {
                    conn = mycon.con;
                    String query = "delete from admin where employeeid=?";
                    pstmt = conn.prepareStatement(query);
                    pstmt.setString(1, txtemployeeid.getText().toUpperCase());
                    pstmt.execute();
                    
                    JOptionPane.showMessageDialog(this, "Data has been deleted");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeaccountadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeaccountadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeaccountadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeaccountadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeaccountadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblemployeeid;
    private javax.swing.JTable tbladmin;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtemployeeid;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtmiddlename;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
