/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informationSystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author castillo
 */
public class clerkmain extends javax.swing.JFrame {
    DBconnetion mycon = new DBconnetion();
    Connection conn;
    PreparedStatement pstmt;
    Statement stmt;
    ResultSet rs;
    
    public clerkmain() {
        initComponents();
        mycon.doConnect();
        center();
        
    }
    
       void center(){
     
         Dimension screen = Toolkit.getDefaultToolkit().getScreenSize() ;
Dimension jscreen = this.getSize();

this.setLocation((screen.width - jscreen.width)/2, ((screen.height-jscreen.height)/2)-90);

 }
public void close(){
    WindowEvent winclose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellogin = new javax.swing.JPanel();
        btnlogin = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panellogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panellogin.setLayout(null);

        btnlogin.setText("Log In");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        btnlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnloginKeyReleased(evt);
            }
        });
        panellogin.add(btnlogin);
        btnlogin.setBounds(240, 210, 170, 30);

        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuserKeyReleased(evt);
            }
        });
        panellogin.add(txtuser);
        txtuser.setBounds(210, 130, 220, 30);

        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
        });
        panellogin.add(txtpass);
        txtpass.setBounds(210, 170, 220, 30);

        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panellogin.add(jButton2);
        jButton2.setBounds(150, 210, 80, 30);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panellogin.add(jButton1);
        jButton1.setBounds(90, 210, 51, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loginwallpaper.png"))); // NOI18N
        panellogin.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogin, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
       if(txtuser.getText().isEmpty() && txtpass.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Please enter your username and password");
       }else{
           PreparedStatement deletelogindummy;
                  try {
            conn = mycon.con;
            String querycheck = "select * from clerk where username=? and password=?";
            pstmt = conn.prepareStatement(querycheck);
            pstmt.setString(1, txtuser.getText().toUpperCase());
            pstmt.setString(2, txtpass.getText().toUpperCase());
            rs = pstmt.executeQuery();
            
            if(rs.next()){
                String querylogindummy = "delete from logindummy";
                pstmt = conn.prepareStatement(querylogindummy);
                pstmt.execute();
                
                String query = "insert into logindummy values(?,?)";
                pstmt = conn.prepareStatement(query);
                pstmt.setString(1, txtuser.getText().toUpperCase());
                pstmt.setString(2, txtpass.getText().toUpperCase());
                pstmt.execute();
                
                JOptionPane.showMessageDialog(this, "Welcome");
                clerkform clerk = new clerkform();
               clerk.setVisible(true);
               close();
            }else{
                JOptionPane.showMessageDialog(this, "Username and password incorrect");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
       }
             
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnloginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnloginKeyReleased
        conn = mycon.con;
        String query = "select * from admin where username=? and password=?";
        try {
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                 pstmt=conn.prepareStatement(query);
            pstmt.setString(1, txtuser.getText());
            pstmt.setString(2, txtpass.getText());
            rs=pstmt.executeQuery();
            
            

            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome");
                
                   try {
                    conn = mycon.con;
                    String logindummy = "insert into logindummy values(?,?)";
                    pstmt = conn.prepareStatement(logindummy);
                    pstmt.setString(1, txtuser.getText());
                    pstmt.setString(2, txtpass.getText());
                    pstmt.execute();
                } catch (Exception e) {
                }
                clerkhome home = new clerkhome();
                home.setVisible(true);
                close();
            }else{
                JOptionPane.showMessageDialog(null, "Please enter username and password correctly");
                txtuser.setText(null);
                txtpass.setText(null);
                panellogin.requestFocus();
            }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Log in error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnloginKeyReleased

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
              if(txtuser.getText().isEmpty() && txtpass.getText().isEmpty()){
                  JOptionPane.showMessageDialog(this, "Please enter first the username and password");
              }else{
                  PreparedStatement deletelogindummy;
                  try {
            conn = mycon.con;
            String querycheck = "select * from clerk where username=? and password=?";
            pstmt = conn.prepareStatement(querycheck);
            pstmt.setString(1, txtuser.getText().toUpperCase());
            pstmt.setString(2, txtpass.getText().toUpperCase());
            rs = pstmt.executeQuery();
            
            if(rs.next()){
                String querylogindummy = "delete from logindummy";
                pstmt = conn.prepareStatement(querylogindummy);
                pstmt.execute();
                
                String query = "insert into logindummy values(?,?)";
                pstmt = conn.prepareStatement(query);
                pstmt.setString(1, txtuser.getText().toUpperCase());
                pstmt.setString(2, txtpass.getText().toUpperCase());
                pstmt.execute();
                
                JOptionPane.showMessageDialog(this, "Welcome");
                clerkform clerk = new clerkform();
               clerk.setVisible(true);
               close();
            }else{
                JOptionPane.showMessageDialog(this, "Username and password incorrect");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
              }
          }
       
    }//GEN-LAST:event_txtpassKeyReleased

    private void txtuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyReleased
           if(evt.getKeyCode() == KeyEvent.VK_ENTER){
              if(txtuser.getText().isEmpty() && txtpass.getText().isEmpty()){
                  JOptionPane.showMessageDialog(this, "Please enter first the username and password");
              }else{
                  PreparedStatement deletelogindummy;
                  try {
            conn = mycon.con;
            String querycheck = "select * from clerk where username=? and password=?";
            pstmt = conn.prepareStatement(querycheck);
            pstmt.setString(1, txtuser.getText().toUpperCase());
            pstmt.setString(2, txtpass.getText().toUpperCase());
            rs = pstmt.executeQuery();
            
            if(rs.next()){
                String querylogindummy = "delete from logindummy";
                pstmt = conn.prepareStatement(querylogindummy);
                pstmt.execute();
                
                String query = "insert into logindummy values(?,?)";
                pstmt = conn.prepareStatement(query);
                pstmt.setString(1, txtuser.getText().toUpperCase());
                pstmt.setString(2, txtpass.getText().toUpperCase());
                pstmt.execute();
                
                JOptionPane.showMessageDialog(this, "Welcome");
                clerkform clerk = new clerkform();
               clerk.setVisible(true);
               close();
            }else{
                JOptionPane.showMessageDialog(this, "Username and password incorrect");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
              }
          }
    }//GEN-LAST:event_txtuserKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        System.exit(0);
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectframe select = new selectframe();
        select.setVisible(true);
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    Thread.sleep(4500);
                } catch (Exception e) {
                    
                }
                
                new main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
