/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informationSystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.olap4j.PreparedOlapStatement;

/**
 *
 * @author castillo
 */
public class gradeandsubjectviewrecord extends javax.swing.JInternalFrame {
        DBconnetion mycon = new DBconnetion();
        Connection conn;
        PreparedStatement pstmt;
        Statement stmt;
        ResultSet rs;
        String enrollid;
    public gradeandsubjectviewrecord() {
        initComponents();
        mycon.doConnect();
        subject();
    }
    void subject(){
        Statement record;
        ResultSet recordresult;
        
        try {
            Statement graderecord;
        ResultSet graderecordresult;
          conn = mycon.con;
          stmt = conn.createStatement();
          rs = stmt.executeQuery("select * from enrollstudentgradedummy");
          
          if(rs.next()){
              enrollid = rs.getString(1);
          }
          
          graderecord = conn.createStatement();
          graderecordresult = graderecord.executeQuery("SELECT \n" +
"  subject.subjectid, \n" +
"  subject.subjecttitle, \n" +
"  grade.subjectgrade\n" +
"FROM \n" +
"  public.subject, \n" +
"  public.grade\n" +
"WHERE \n" +
"  subject.subjectid = grade.subjectid and grade.enrollstudentid='" + enrollid + "'");
          DefaultTableModel model = ((DefaultTableModel)tblsearch.getModel());
          model.getDataVector().removeAllElements();
          
          while(graderecordresult.next()){
              model.addRow(new Object[] {graderecordresult.getString(1), graderecordresult.getString(2), graderecordresult.getString(3)});
          }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblsearch = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tblsearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject ID", "Title", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tblsearch);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Search");

        btnsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnsearchKeyReleased(evt);
            }
        });

        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search)
                        .addComponent(btnsearch)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    Statement record;
        ResultSet recordresult;
            try {
            Statement graderecord;
        ResultSet graderecordresult;
          conn = mycon.con;
          stmt = conn.createStatement();
          rs = stmt.executeQuery("select * from enrollstudentgradedummy");
          
          if(rs.next()){
              enrollid = rs.getString(1);
          }
          
          graderecord = conn.createStatement();
          graderecordresult = graderecord.executeQuery("SELECT \n" +
"  subject.subjectid, \n" +
"  subject.subjecttitle, \n" +
"  grade.subjectgrade\n" +
"FROM \n" +
"  public.subject, \n" +
"  public.grade\n" +
"WHERE \n" +
"  subject.subjectid = grade.subjectid and grade.enrollstudentid='" + enrollid + "' and subject.subjecttitle like'" + btnsearch.getText().toUpperCase() + "'");
          DefaultTableModel model = ((DefaultTableModel)tblsearch.getModel());
          model.getDataVector().removeAllElements();
          
          while(graderecordresult.next()){
              model.addRow(new Object[] {graderecordresult.getString(1), graderecordresult.getString(2), graderecordresult.getString(3)});
          }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void btnsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsearchKeyReleased
        Statement record;
        ResultSet recordresult;
            try {
            Statement graderecord;
        ResultSet graderecordresult;
          conn = mycon.con;
          stmt = conn.createStatement();
          rs = stmt.executeQuery("select * from enrollstudentgradedummy");
          
          if(rs.next()){
              enrollid = rs.getString(1);
          }
          
          graderecord = conn.createStatement();
          graderecordresult = graderecord.executeQuery("SELECT \n" +
"  subject.subjectid, \n" +
"  subject.subjecttitle, \n" +
"  grade.subjectgrade\n" +
"FROM \n" +
"  public.subject, \n" +
"  public.grade\n" +
"WHERE \n" +
"  subject.subjectid = grade.subjectid and grade.enrollstudentid='" + enrollid + "' and subject.subjecttitle like'" + btnsearch.getText().toUpperCase() + "'");
          DefaultTableModel model = ((DefaultTableModel)tblsearch.getModel());
          model.getDataVector().removeAllElements();
          
          while(graderecordresult.next()){
              model.addRow(new Object[] {graderecordresult.getString(1), graderecordresult.getString(2), graderecordresult.getString(3)});
          }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_btnsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
          conn = mycon.con;
          String query = "delete from enrollstudentgradedummy";
          pstmt = conn.prepareStatement(query);
          pstmt.execute();
          this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        subject();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btnsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTable tblsearch;
    // End of variables declaration//GEN-END:variables
}
