/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informationSystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author castillo
 */
public class informationsystemhome extends javax.swing.JFrame {

    DBconnetion mycon = new DBconnetion();
    Connection conn;
    PreparedStatement pstmt;
    Statement stmt;
    ResultSet rs;
    
    public informationsystemhome() {
        initComponents();
        mycon.doConnect();
        center();
        timer();
        user();
        logindummy();
        employeeid();

        
        


        
    }
    
    
    void user(){
        conn = mycon.con;
        
    }
    
    void timer(){
     Timer t = new Timer(1000,new Listener());
     t.start();
    
}
class Listener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            Date date = Calendar.getInstance().getTime();
            SimpleDateFormat frmtime = new SimpleDateFormat("hh:mm:ss a");
            String timenow = frmtime.format(date);
            lbltime.setText(timenow.toString());

            Format frmt = new SimpleDateFormat("MMMMM dd, yyyy");
            String dshow = frmt.format(date); 
            lbldate.setText(dshow.toString());
        }
}
    
     void center(){

    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize() ;
    Dimension jscreen = this.getSize();

    this.setLocation((screen.width - jscreen.width)/2, ((screen.height-jscreen.height)/2)-90);

    } 
    
    public void close(){
    WindowEvent winclose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
}
    
    void logindummy(){
    Connection con = mycon.con;
    ResultSet rsdummmy;
    Statement stmtdummy;
    
        try {
            stmtdummy = con.createStatement();
            rsdummmy = stmtdummy.executeQuery("select username from logindummy");
            String user;
            
            if(rsdummmy.next()){
                
                user = rsdummmy.getString(1).toString();
                lbluser.setText(user);
                
            }
        } catch (Exception e) {
        }
}
    void employeeid(){
        try {
            Connection con = mycon.con;
            ResultSet rsemployeeid;
            Statement stmtemployeeid;
            
            try {
                stmtemployeeid = con.createStatement();
                rsemployeeid = stmtemployeeid.executeQuery("select * from admin where username like'" + lbluser.getText() + "%'");
                String employeeID;
                if(rsemployeeid.next()){
                    employeeID = rsemployeeid.getString(1).toString();
                    lblemployeeid.setText(employeeID);
                }
            } catch (Exception e) {
            }
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2 = new javax.swing.JInternalFrame();
        btnevaluate = new javax.swing.JButton();
        btnteacher = new javax.swing.JButton();
        btnsubject = new javax.swing.JButton();
        btngrades = new javax.swing.JButton();
        btnreports = new javax.swing.JButton();
        btnenroll = new javax.swing.JButton();
        btnsettings = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lblemployeeid = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        btnevaluate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/studenticon.png"))); // NOI18N
        btnevaluate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnevaluateActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnevaluate);
        btnevaluate.setBounds(40, 260, 135, 43);

        btnteacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/teachericon.png"))); // NOI18N
        btnteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnteacherActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnteacher);
        btnteacher.setBounds(40, 310, 135, 43);

        btnsubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/subjecticon.png"))); // NOI18N
        btnsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubjectActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnsubject);
        btnsubject.setBounds(210, 210, 135, 43);

        btngrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gradesicon.png"))); // NOI18N
        btngrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngradesActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btngrades);
        btngrades.setBounds(210, 260, 135, 43);

        btnreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reporticon.png"))); // NOI18N
        btnreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportsActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnreports);
        btnreports.setBounds(210, 310, 135, 43);

        btnenroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/enroll.png"))); // NOI18N
        btnenroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenrollActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnenroll);
        btnenroll.setBounds(40, 210, 135, 40);

        btnsettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settingsicon.png"))); // NOI18N
        btnsettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsettingsActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnsettings);
        btnsettings.setBounds(620, 380, 60, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/header.jpg"))); // NOI18N
        jInternalFrame2.getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 370, 700, 150);

        lbluser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbluser.setText("user");
        lbluser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbluserKeyReleased(evt);
            }
        });
        jInternalFrame2.getContentPane().add(lbluser);
        lbluser.setBounds(410, 200, 170, 22);

        lblemployeeid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblemployeeid.setText("employer ID");
        jInternalFrame2.getContentPane().add(lblemployeeid);
        lblemployeeid.setBounds(410, 230, 190, 22);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logouticon.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton7);
        jButton7.setBounds(603, 180, 80, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Time:");
        jInternalFrame2.getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 300, 51, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Date:");
        jInternalFrame2.getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 330, 50, 22);

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltime.setText("time");
        jInternalFrame2.getContentPane().add(lbltime);
        lbltime.setBounds(470, 300, 200, 22);

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldate.setText("date");
        jInternalFrame2.getContentPane().add(lbldate);
        lbldate.setBounds(470, 330, 200, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sksuwallpaper.png"))); // NOI18N
        jInternalFrame2.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -4, 700, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int ask = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?","Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(ask == JOptionPane.YES_OPTION){
            
            try {
                conn = mycon.con;
                String logout = "delete from logindummy";
                pstmt = conn.prepareStatement(logout);
                pstmt.execute();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
            
        main infosystem = new main();
        infosystem.setVisible(true);
            close();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnenrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenrollActionPerformed
        enroll enrollbutton = new enroll();
        enrollbutton.setVisible(true);
        close();
    }//GEN-LAST:event_btnenrollActionPerformed

    private void lbluserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbluserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbluserKeyReleased

    private void btnsettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsettingsActionPerformed
        settings settingsadmin = new settings();
        settingsadmin.setVisible(true);


        


    }//GEN-LAST:event_btnsettingsActionPerformed

    private void btnsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubjectActionPerformed
        subject studentsubject = new subject();
        studentsubject.setVisible(true);
        close();
    }//GEN-LAST:event_btnsubjectActionPerformed

    private void btnteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnteacherActionPerformed
       registerteacher studentteacher = new registerteacher();
       studentteacher.setVisible(true);
       close();
    }//GEN-LAST:event_btnteacherActionPerformed

    private void btnevaluateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnevaluateActionPerformed
        studentform student = new studentform();
        student.setVisible(true);
        close();
    }//GEN-LAST:event_btnevaluateActionPerformed

    private void btngradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngradesActionPerformed
         studentgrade studentgraderecord = new studentgrade();
         studentgraderecord.setVisible(true);
         close();
         
        
        
      
    }//GEN-LAST:event_btngradesActionPerformed

    private void btnreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportsActionPerformed
        report recordreport = new report();
        recordreport.setVisible(true);
        close();
    }//GEN-LAST:event_btnreportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informationsystemhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informationsystemhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informationsystemhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informationsystemhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informationsystemhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenroll;
    private javax.swing.JButton btnevaluate;
    private javax.swing.JButton btngrades;
    private javax.swing.JButton btnreports;
    private javax.swing.JButton btnsettings;
    private javax.swing.JButton btnsubject;
    private javax.swing.JButton btnteacher;
    private javax.swing.JButton jButton7;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblemployeeid;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lbluser;
    // End of variables declaration//GEN-END:variables
}
