/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informationSystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author castillo
 */
public class studentdatarecord extends javax.swing.JInternalFrame {
        DBconnetion mycon = new DBconnetion();
        Connection conn;
        PreparedStatement pstmt;
        Statement stmt;
        ResultSet rs;
        String studentaccountnumber;
        String accountnumber;
    public studentdatarecord() {
        initComponents();
        mycon.doConnect();
        studentinformation();
        schoolyear();
    }
    
    void studentinformation(){
        try {
            conn = mycon.con;
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select * from student");
            
            DefaultTableModel model = ((DefaultTableModel)tblstudentinformation.getModel());
            model.getDataVector().removeAllElements();
            
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }
    

           void schoolyear(){
               try {
                   conn = mycon.con;
               stmt = conn.createStatement();
                rs = stmt.executeQuery("select year from schoolyear");
                
                while(rs.next()){
                    cbgrade7schoolyear.addItem(rs.getString(1));
                    cbgrade8schoolyear.addItem(rs.getString(1));
                    cbgrade9schoolyear.addItem(rs.getString(1));
                    cbgrade10schoolyear.addItem(rs.getString(1));
                    cbgrade11schoolyear.addItem(rs.getString(1));
                    cbgrade12schoolyear.addItem(rs.getString(1));
                    
                }
               } catch (Exception e) {
               }
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtstudentfatherlastname = new javax.swing.JTextField();
        txtstudentfatherfirstname = new javax.swing.JTextField();
        txtstudentmotherfirstname = new javax.swing.JTextField();
        txtmiddlename = new javax.swing.JTextField();
        txtdateofbirth = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtstudentfathermiddlename = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtstudentmothermiddlename = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtoccupation = new javax.swing.JTextField();
        txtstudentmotherlastname = new javax.swing.JTextField();
        txtnameofguardian = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbgender = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtplaceofbirth = new javax.swing.JTextField();
        txtaddressofguardian = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblstudentinformation = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtreligion = new javax.swing.JTextField();
        txttribe = new javax.swing.JTextField();
        txtcitizenship = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtgrade7 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtgrade8 = new javax.swing.JTextField();
        txtgrade9 = new javax.swing.JTextField();
        txtgrade10 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cbgrade7schoolyear = new javax.swing.JComboBox<>();
        cbgrade8schoolyear = new javax.swing.JComboBox<>();
        cbgrade9schoolyear = new javax.swing.JComboBox<>();
        cbgrade10schoolyear = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtgrade11 = new javax.swing.JTextField();
        txtgrade12 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cbgrade11schoolyear = new javax.swing.JComboBox<>();
        cbgrade12schoolyear = new javax.swing.JComboBox<>();
        txtelementary = new javax.swing.JTextField();
        txtintermediate = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setClosable(true);

        jPanel4.setLayout(null);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registerwallpaper.png"))); // NOI18N
        jPanel4.add(jLabel36);
        jLabel36.setBounds(0, 0, 1030, 70);

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonicons/Student-id-icon.png"))); // NOI18N
        jButton6.setText("Enroll Student");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton6);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonicons/Delete-icon (1).png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonicons/Button-Refresh-icon.png"))); // NOI18N
        jButton4.setText("Update");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonicons/clear icon.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel8.setText("Place of Birth");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel19.setText("Middlename");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("Lastname");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Firstname");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel11.setText("Occupation");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel13.setText("Student Father:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel10.setText("Name of Guardian");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel9.setText("Address");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel7.setText("Date of Birth");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel18.setText("Firstname");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("Gender");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Middlename");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel14.setText("Firstname");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel6.setText("Age");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel12.setText("Address of Guardian");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel17.setText("Student Mother:");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel20.setText("Lastname");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel16.setText("Lastname");

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel15.setText("Middlename");

        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtageKeyTyped(evt);
            }
        });

        tblstudentinformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account Number", "Firstname", "Middlename", "Lastname"
            }
        ));
        tblstudentinformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstudentinformationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblstudentinformation);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel40.setText("Search");

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtlastname)
                            .addComponent(txtmiddlename)
                            .addComponent(txtfirstname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtage)
                            .addComponent(txtdateofbirth)
                            .addComponent(txtplaceofbirth)
                            .addComponent(txtaddress)
                            .addComponent(txtnameofguardian)
                            .addComponent(txtoccupation)
                            .addComponent(txtaddressofguardian)
                            .addComponent(txtstudentfatherfirstname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtstudentfathermiddlename)
                            .addComponent(txtstudentfatherlastname)
                            .addComponent(txtstudentmotherfirstname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtstudentmothermiddlename, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtstudentmotherlastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbgender, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtplaceofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnameofguardian, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtaddressofguardian, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstudentfatherfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstudentfathermiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstudentfatherlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstudentmotherfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstudentmothermiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstudentmotherlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel21.setText("Religion");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel22.setText("Tribe");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel23.setText("Citizenship");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Junior"));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel24.setText("Grade 7");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel25.setText("Grade 7 Schoolyear");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel26.setText("Grade 8");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel27.setText("Grade 8 Schoolyear");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel28.setText("Grade 9");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel29.setText("Grade 9 Schoolyear");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel30.setText("Grade 10");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel31.setText("Grade 10 Schoolyear");

        cbgrade7schoolyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cbgrade8schoolyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cbgrade9schoolyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cbgrade10schoolyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(txtgrade7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtgrade9, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbgrade8schoolyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtgrade8, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(cbgrade7schoolyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbgrade10schoolyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbgrade9schoolyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtgrade10, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txtgrade7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbgrade7schoolyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgrade8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(cbgrade8schoolyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgrade9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(cbgrade9schoolyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgrade10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cbgrade10schoolyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Senior"));

        txtgrade11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrade11ActionPerformed(evt);
            }
        });

        txtgrade12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrade12ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel32.setText("Grade 11");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel33.setText("Grade 11 Schoolyear");

        jLabel34.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel34.setText("Grade 12");

        jLabel35.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel35.setText("Grade 12 Schoolyear");

        cbgrade11schoolyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cbgrade12schoolyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(txtgrade11, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbgrade12schoolyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbgrade11schoolyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtgrade12, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgrade11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(5, 5, 5)
                        .addComponent(cbgrade11schoolyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgrade12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cbgrade12schoolyear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel37.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel37.setText("Elementary");

        jLabel38.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel38.setText("Intermediate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttribe, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtreligion, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtelementary, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtintermediate, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtreligion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(txttribe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtelementary, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtintermediate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgrade11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrade11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrade11ActionPerformed

    private void txtgrade12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrade12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrade12ActionPerformed

    private void txtageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyTyped
        char savebutton = evt.getKeyChar();
        if(!(Character.isDigit(savebutton)) || (savebutton == KeyEvent.VK_BACK_SPACE) || (savebutton == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtageKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int askdelete = JOptionPane.showConfirmDialog(this, "Do you want to delete this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(askdelete == JOptionPane.YES_OPTION){
            PreparedStatement ernollstudent;
            PreparedStatement enrolladdsubject;
            PreparedStatement enrollstudentrecord;
            try {
                conn = mycon.con;
                String querydelete = "delete from student where accountnumber=?";
                pstmt = conn.prepareStatement(querydelete);
                pstmt.setString(1, accountnumber);
                pstmt.execute();
                
                String queryenrollstudent = "delete from ernollstudent where accountnumber=?";
                ernollstudent = conn.prepareStatement(queryenrollstudent);
                ernollstudent.setString(1, accountnumber);
                ernollstudent.execute();
                
                String queryenrolladdsubject = "delete from enrolladdsubject where accountnumber=?";
                enrolladdsubject = conn.prepareStatement(queryenrolladdsubject);
                enrolladdsubject.setString(1, accountnumber);
                enrolladdsubject.execute();
                
                String queryenrollstudentrecord = "delete from enrollstudentrecord where accountnumber=?";
                enrollstudentrecord = conn.prepareStatement(queryenrollstudentrecord);
                enrollstudentrecord.setString(1, accountnumber);
                enrollstudentrecord.execute();
                
                JOptionPane.showMessageDialog(this, "Data has been deleted");
                    accountnumber = null;
                txtfirstname.setText(null);
                txtmiddlename.setText(null);
                txtlastname.setText(null);
                cbgender.setSelectedIndex(0);
                txtage.setText(null);
                txtdateofbirth.setText(null);
                txtplaceofbirth.setText(null);
                txtaddress.setText(null);
                txtnameofguardian.setText(null);
                txtoccupation.setText(null);
                txtaddressofguardian.setText(null);
                txtstudentfatherfirstname.setText(null);
                txtstudentfathermiddlename.setText(null);
                txtstudentfatherlastname.setText(null);
                txtstudentmotherfirstname.setText(null);
                txtstudentmothermiddlename.setText(null);
                txtstudentmotherlastname.setText(null);
                txtreligion.setText(null);
                txttribe.setText(null);
                txtcitizenship.setText(null);
                txtelementary.setText(null);
                txtintermediate.setText(null);
                txtgrade7.setText(null);
                cbgrade7schoolyear.setSelectedIndex(0);
                txtgrade8.setText(null);
                cbgrade8schoolyear.setSelectedIndex(0);
                txtgrade9.setText(null);
                cbgrade9schoolyear.setSelectedIndex(0);
                txtgrade10.setText(null);
                cbgrade10schoolyear.setSelectedIndex(0);
                txtgrade11.setText(null);
                cbgrade11schoolyear.setSelectedIndex(0);
                txtgrade12.setText(null);
                cbgrade12schoolyear.setSelectedIndex(0);
                studentinformation();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int askupdate = JOptionPane.showConfirmDialog(this, "Do you want to update this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(askupdate == JOptionPane.YES_OPTION){
            PreparedStatement ernollstudentrecord;
            PreparedStatement enrolladdsubjectrecord;
            PreparedStatement enrollstudentrecord;
            try {
                conn = mycon.con;
                
                
            
            
            String queryupdate = "update student set studfirst=?, studmiddle=?, studlast=?, studgender=?, studage=?, dateofbirth=?, placeofbirth=?, address=?, nameofguardian=?, occupation=?, addressofguardian=?, studfatherfirstname=?, studfathermiddlename=?, studfatherlastname=?, studmotherfirstname=?, studmothermiddlename=?, studmotherlastname=?, religion=?, tribe=?, citizenship=?, elementary=?, intermediate=?, grade7=?, grade7schoolyear=?, grade8=?, grade8schoolyear=?, grade9=?, grade9schoolyear=?, grade10=?, grade10schoolyear=?, grade11=?, grade11schoolyear=?, grade12=?, grade12schoolyear=? where accountnumber=?";
            pstmt = conn.prepareStatement(queryupdate);
                          
                pstmt.setString(1, txtfirstname.getText().toUpperCase());
                pstmt.setString(2, txtmiddlename.getText().toUpperCase());
                pstmt.setString(3, txtlastname.getText().toUpperCase());
                pstmt.setString(4, cbgender.getSelectedItem().toString().toUpperCase());
                pstmt.setInt(5, Integer.parseInt(txtage.getText()));
                pstmt.setString(6, txtdateofbirth.getText().toUpperCase());
                pstmt.setString(7, txtplaceofbirth.getText().toUpperCase());
                pstmt.setString(8, txtaddress.getText().toUpperCase());
                pstmt.setString(9, txtnameofguardian.getText().toUpperCase());
                pstmt.setString(10, txtoccupation.getText().toUpperCase());
                pstmt.setString(11, txtaddressofguardian.getText().toUpperCase());
                pstmt.setString(12, txtstudentfatherfirstname.getText().toUpperCase());
                pstmt.setString(13, txtstudentfathermiddlename.getText().toUpperCase());
                pstmt.setString(14, txtstudentfatherlastname.getText().toUpperCase());
                pstmt.setString(15, txtstudentmotherfirstname.getText().toUpperCase());
                pstmt.setString(16, txtstudentmothermiddlename.getText().toUpperCase());
                pstmt.setString(17, txtstudentmotherlastname.getText().toUpperCase());
                pstmt.setString(18, txtreligion.getText().toUpperCase());
                pstmt.setString(19, txttribe.getText().toUpperCase());
                pstmt.setString(20, txtcitizenship.getText().toUpperCase());
                pstmt.setString(21, txtelementary.getText().toUpperCase());
                pstmt.setString(22, txtintermediate.getText().toUpperCase());
                pstmt.setString(23, txtgrade7.getText().toUpperCase());
                pstmt.setString(24, cbgrade7schoolyear.getSelectedItem().toString());
                pstmt.setString(25, txtgrade8.getText().toUpperCase());
                pstmt.setString(26, cbgrade8schoolyear.getSelectedItem().toString());
                pstmt.setString(27, txtgrade9.getText().toUpperCase());
                pstmt.setString(28, cbgrade9schoolyear.getSelectedItem().toString());
                pstmt.setString(29, txtgrade10.getText().toUpperCase());
                pstmt.setString(30, cbgrade10schoolyear.getSelectedItem().toString());
                pstmt.setString(31, txtgrade11.getText().toUpperCase());
                pstmt.setString(32, cbgrade11schoolyear.getSelectedItem().toString());
                pstmt.setString(33, txtgrade12.getText().toUpperCase());
                pstmt.setString(34, cbgrade12schoolyear.getSelectedItem().toString());
                pstmt.setString(35, accountnumber);
                pstmt.execute();
                
                String ernollinformation = "update ernollstudent set accountnumber=? where accountnumber=?";
                ernollstudentrecord = conn.prepareStatement(ernollinformation);
                ernollstudentrecord.setString(1, accountnumber);
                ernollstudentrecord.setString(2, accountnumber);
                ernollstudentrecord.execute();
                
                String enrolladdsubject = "update enrolladdsubject set accountnumber=? where accountnumber=?";
                enrolladdsubjectrecord = conn.prepareStatement(enrolladdsubject);
                enrolladdsubjectrecord.setString(1, accountnumber);
                enrolladdsubjectrecord.setString(2, accountnumber);
                enrolladdsubjectrecord.execute();
                
                String enrollinformation = "update enrollstudentrecord set accountnumber=? where accountnumber=?";
                enrollstudentrecord = conn.prepareStatement(enrollinformation);
                enrollstudentrecord.setString(1, accountnumber);
                enrollstudentrecord.setString(2, accountnumber);
                enrollstudentrecord.execute();
                
                
                JOptionPane.showMessageDialog(this, "Data has been updated");
                             
                txtfirstname.setText(null);
                txtmiddlename.setText(null);
                txtlastname.setText(null);
                cbgender.setSelectedIndex(0);
                txtage.setText(null);
                txtdateofbirth.setText(null);
                txtplaceofbirth.setText(null);
                txtaddress.setText(null);
                txtnameofguardian.setText(null);
                txtoccupation.setText(null);
                txtaddressofguardian.setText(null);
                txtreligion.setText(null);
                txttribe.setText(null);
                txtcitizenship.setText(null);
                txtelementary.setText(null);
                txtintermediate.setText(null);
                txtgrade7.setText(null);
                cbgrade7schoolyear.setSelectedIndex(0);
                txtgrade8.setText(null);
                cbgrade8schoolyear.setSelectedIndex(0);
                txtgrade9.setText(null);
                cbgrade9schoolyear.setSelectedIndex(0);
                txtgrade10.setText(null);
                cbgrade10schoolyear.setSelectedIndex(0);
                txtgrade11.setText(null);
                cbgrade11schoolyear.setSelectedIndex(0);
                txtgrade12.setText(null);
                cbgrade12schoolyear.setSelectedIndex(0);
                studentinformation();
           
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(txtsearch.getText().isEmpty()){
                
                txtfirstname.setText(null);
                txtmiddlename.setText(null);
                txtlastname.setText(null);
                cbgender.setSelectedIndex(0);
                txtage.setText(null);
                txtdateofbirth.setText(null);
                txtplaceofbirth.setText(null);
                txtaddress.setText(null);
                txtnameofguardian.setText(null);
                txtoccupation.setText(null);
                txtaddressofguardian.setText(null);
                txtstudentfatherfirstname.setText(null);
                txtstudentfathermiddlename.setText(null);
                txtstudentfatherlastname.setText(null);
                txtstudentmotherfirstname.setText(null);
                txtstudentmothermiddlename.setText(null);
                txtstudentmotherlastname.setText(null);
                txtreligion.setText(null);
                txttribe.setText(null);
                txtcitizenship.setText(null);
                txtelementary.setText(null);
                txtintermediate.setText(null);
                txtgrade7.setText(null);
                cbgrade7schoolyear.setSelectedIndex(0);
                txtgrade8.setText(null);
                cbgrade8schoolyear.setSelectedIndex(0);
                txtgrade9.setText(null);
                cbgrade9schoolyear.setSelectedIndex(0);
                txtgrade10.setText(null);
                cbgrade10schoolyear.setSelectedIndex(0);
                txtgrade11.setText(null);
                cbgrade11schoolyear.setSelectedIndex(0);
                txtgrade12.setText(null);
                cbgrade12schoolyear.setSelectedIndex(0);

            }else{
                try {
                    conn = mycon.con;
                    stmt = conn.createStatement();
                    rs = stmt.executeQuery("select * from student where studfirst like'" + txtsearch.getText().toUpperCase() + "%' or studmiddle like'" + txtsearch.getText().toUpperCase() + "%' or studlast like'" + txtsearch.getText().toUpperCase() + "%' or accountnumber like'" + txtsearch.getText().toUpperCase() + "%'");
DefaultTableModel model = ((DefaultTableModel)tblstudentinformation.getModel());
            model.getDataVector().removeAllElements();
            
            
                    while(rs.next()){
                         model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
                        
                        txtfirstname.setText(rs.getString(2));
                        txtmiddlename.setText(rs.getString(3));
                        txtlastname.setText(rs.getString(4));
                        cbgender.setSelectedItem(rs.getString(5));
                        txtage.setText(rs.getString(6));
                        txtplaceofbirth.setText(rs.getString(7));
                        txtdateofbirth.setText(rs.getString(8));
                        txtaddress.setText(rs.getString(9));
                        txtnameofguardian.setText(rs.getString(10));
                        txtoccupation.setText(rs.getString(11));
                        txtaddressofguardian.setText(rs.getString(12));
                        txtstudentfatherfirstname.setText(rs.getString(13));
                        txtstudentfathermiddlename.setText(rs.getString(14));
                        txtstudentfatherlastname.setText(rs.getString(15));
                        txtstudentmotherfirstname.setText(rs.getString(16));
                        txtstudentmothermiddlename.setText(rs.getString(17));
                        txtstudentmotherlastname.setText(rs.getString(18));
                        txtreligion.setText(rs.getString(19));
                        txttribe.setText(rs.getString(20));
                        txtcitizenship.setText(rs.getString(21));
                        txtelementary.setText(rs.getString(22));
                        txtintermediate.setText(rs.getString(23));
                        txtgrade7.setText(rs.getString(24));
                        cbgrade7schoolyear.setSelectedItem(rs.getString(25));
                        txtgrade8.setText(rs.getString(26));
                        cbgrade8schoolyear.setSelectedItem(rs.getString(27));
                        txtgrade9.setText(rs.getString(28));
                        cbgrade9schoolyear.setSelectedItem(rs.getString(29));
                        txtgrade10.setText(rs.getString(30));
                        cbgrade10schoolyear.setSelectedItem(rs.getString(31));
                        txtgrade11.setText(rs.getString(32));
                        cbgrade11schoolyear.setSelectedItem(rs.getString(33));
                        txtgrade12.setText(rs.getString(34));
                        cbgrade12schoolyear.setSelectedItem(rs.getString(35));
                        studentaccountnumber = rs.getString(1);

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conn = mycon.con;
                    stmt = conn.createStatement();
                    rs = stmt.executeQuery("select * from student where studfirst like'" + txtsearch.getText().toUpperCase() + "%' or studmiddle like'" + txtsearch.getText().toUpperCase() + "%' or studlast like'" + txtsearch.getText().toUpperCase() + "%' or accountnumber like'" + txtsearch.getText().toUpperCase() + "%'");
       DefaultTableModel model = ((DefaultTableModel)tblstudentinformation.getModel());
            model.getDataVector().removeAllElements();
            
                    while(rs.next()){
                         model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
                        
                        txtfirstname.setText(rs.getString(2));
                        txtmiddlename.setText(rs.getString(3));
                        txtlastname.setText(rs.getString(4));
                        cbgender.setSelectedItem(rs.getString(5));
                        txtage.setText(rs.getString(6));
                        txtplaceofbirth.setText(rs.getString(7));
                        txtdateofbirth.setText(rs.getString(8));
                        txtaddress.setText(rs.getString(9));
                        txtnameofguardian.setText(rs.getString(10));
                        txtoccupation.setText(rs.getString(11));
                        txtaddressofguardian.setText(rs.getString(12));
                        txtstudentfatherfirstname.setText(rs.getString(13));
                        txtstudentfathermiddlename.setText(rs.getString(14));
                        txtstudentfatherlastname.setText(rs.getString(15));
                        txtstudentmotherfirstname.setText(rs.getString(16));
                        txtstudentmothermiddlename.setText(rs.getString(17));
                        txtstudentmotherlastname.setText(rs.getString(18));
                        txtreligion.setText(rs.getString(19));
                        txttribe.setText(rs.getString(20));
                        txtcitizenship.setText(rs.getString(21));
                        txtelementary.setText(rs.getString(22));
                        txtintermediate.setText(rs.getString(23));
                        txtgrade7.setText(rs.getString(24));
                        cbgrade7schoolyear.setSelectedItem(rs.getString(25));
                        txtgrade8.setText(rs.getString(26));
                        cbgrade8schoolyear.setSelectedItem(rs.getString(27));
                        txtgrade9.setText(rs.getString(28));
                        cbgrade9schoolyear.setSelectedItem(rs.getString(29));
                        txtgrade10.setText(rs.getString(30));
                        cbgrade10schoolyear.setSelectedItem(rs.getString(31));
                        txtgrade11.setText(rs.getString(32));
                        cbgrade11schoolyear.setSelectedItem(rs.getString(33));
                        txtgrade12.setText(rs.getString(34));
                        cbgrade12schoolyear.setSelectedItem(rs.getString(35));
                        studentaccountnumber = rs.getString(1);

                    }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblstudentinformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstudentinformationMouseClicked
        try {
            int studentrow = tblstudentinformation.getSelectedRow();
            
            String studentrow1 = (tblstudentinformation.getModel().getValueAt(studentrow, 0).toString());
            
            conn = mycon.con;
            String studentrowquery = "select * from student where accountnumber='" + studentrow1 + "'";
            pstmt = conn.prepareStatement(studentrowquery);
            rs = pstmt.executeQuery();
            
            while(rs.next()){
                
                        txtfirstname.setText(rs.getString(1));
                        txtmiddlename.setText(rs.getString(2));
                        txtlastname.setText(rs.getString(3));
                        cbgender.setSelectedItem(rs.getString(4));
                        txtage.setText(rs.getString(5));
                        txtplaceofbirth.setText(rs.getString(6));
                        txtdateofbirth.setText(rs.getString(7));
                        txtaddress.setText(rs.getString(8));
                        txtnameofguardian.setText(rs.getString(9));
                        txtoccupation.setText(rs.getString(10));
                        txtaddressofguardian.setText(rs.getString(11));
                        txtstudentfatherfirstname.setText(rs.getString(12));
                        txtstudentfathermiddlename.setText(rs.getString(13));
                        txtstudentfatherlastname.setText(rs.getString(14));
                        txtstudentmotherfirstname.setText(rs.getString(15));
                        txtstudentmothermiddlename.setText(rs.getString(16));
                        txtstudentmotherlastname.setText(rs.getString(17));
                        txtreligion.setText(rs.getString(18));
                        txttribe.setText(rs.getString(19));
                        txtcitizenship.setText(rs.getString(20));
                        txtelementary.setText(rs.getString(21));
                        txtintermediate.setText(rs.getString(22));
                        txtgrade7.setText(rs.getString(23));
                        cbgrade7schoolyear.setSelectedItem(rs.getString(24));
                        txtgrade8.setText(rs.getString(25));
                        cbgrade8schoolyear.setSelectedItem(rs.getString(26));
                        txtgrade9.setText(rs.getString(27));
                        cbgrade9schoolyear.setSelectedItem(rs.getString(28));
                        txtgrade10.setText(rs.getString(29));
                        cbgrade10schoolyear.setSelectedItem(rs.getString(30));
                        txtgrade11.setText(rs.getString(31));
                        cbgrade11schoolyear.setSelectedItem(rs.getString(32));
                        txtgrade12.setText(rs.getString(33));
                        cbgrade12schoolyear.setSelectedItem(rs.getString(34));
                        accountnumber = rs.getString(5);
                        
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_tblstudentinformationMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int askupdate = JOptionPane.showConfirmDialog(this, "Enroll Student?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
        if(askupdate == JOptionPane.YES_OPTION){
            if(txtfirstname.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Search student first");
                txtsearch.setFocusable(true);
            }else{
               PreparedStatement recordenroll;
               PreparedStatement recorddelete;
                try {
                conn = mycon.con;        
            String queryupdate = "update student set studfirst=?, studmiddle=?, studlast=?, studgender=?, studage=?, dateofbirth=?, placeofbirth=?, address=?, nameofguardian=?, occupation=?, addressofguardian=?, studfatherfirstname=?, studfathermiddlename=?, studfatherlastname=?, studmotherfirstname=?, studmothermiddlename=?, studmotherlastname=?, religion=?, tribe=?, citizenship=?, elementary=?, intermediate=?, grade7=?, grade7schoolyear=?, grade8=?, grade8schoolyear=?, grade9=?, grade9schoolyear=?, grade10=?, grade10schoolyear=?, grade11=?, grade11schoolyear=?, grade12=?, grade12schoolyear=? where accountnumber=?";
            pstmt = conn.prepareStatement(queryupdate);
                  
                pstmt.setString(1, txtfirstname.getText().toUpperCase());
                pstmt.setString(2, txtmiddlename.getText().toUpperCase());
                pstmt.setString(3, txtlastname.getText().toUpperCase());
                pstmt.setString(4, cbgender.getSelectedItem().toString().toUpperCase());
                pstmt.setInt(5, Integer.parseInt(txtage.getText()));
                pstmt.setString(6, txtdateofbirth.getText().toUpperCase());
                pstmt.setString(7, txtplaceofbirth.getText().toUpperCase());
                pstmt.setString(8, txtaddress.getText().toUpperCase());
                pstmt.setString(9, txtnameofguardian.getText().toUpperCase());
                pstmt.setString(10, txtoccupation.getText().toUpperCase());
                pstmt.setString(11, txtaddressofguardian.getText().toUpperCase());
                pstmt.setString(12, txtstudentfatherfirstname.getText().toUpperCase());
                pstmt.setString(13, txtstudentfathermiddlename.getText().toUpperCase());
                pstmt.setString(14, txtstudentfatherlastname.getText().toUpperCase());
                pstmt.setString(15, txtstudentmotherfirstname.getText().toUpperCase());
                pstmt.setString(16, txtstudentmothermiddlename.getText().toUpperCase());
                pstmt.setString(17, txtstudentmotherlastname.getText().toUpperCase());
                pstmt.setString(18, txtreligion.getText().toUpperCase());
                pstmt.setString(19, txttribe.getText().toUpperCase());
                pstmt.setString(20, txtcitizenship.getText().toUpperCase());
                pstmt.setString(21, txtelementary.getText().toUpperCase());
                pstmt.setString(22, txtintermediate.getText().toUpperCase());
                pstmt.setString(23, txtgrade7.getText().toUpperCase());
                pstmt.setString(24, cbgrade7schoolyear.getSelectedItem().toString());
                pstmt.setString(25, txtgrade8.getText().toUpperCase());
                pstmt.setString(26, cbgrade8schoolyear.getSelectedItem().toString());
                pstmt.setString(27, txtgrade9.getText().toUpperCase());
                pstmt.setString(28, cbgrade9schoolyear.getSelectedItem().toString());
                pstmt.setString(29, txtgrade10.getText().toUpperCase());
                pstmt.setString(30, cbgrade10schoolyear.getSelectedItem().toString());
                pstmt.setString(31, txtgrade11.getText().toUpperCase());
                pstmt.setString(32, cbgrade11schoolyear.getSelectedItem().toString());
                pstmt.setString(33, txtgrade12.getText().toUpperCase());
                pstmt.setString(34, cbgrade12schoolyear.getSelectedItem().toString());
                pstmt.setString(35, accountnumber);
                pstmt.execute();
                
                String queryenroll = "insert into registertable select * from student where accountnumber=?";
                recordenroll = conn.prepareStatement(queryenroll);
                recordenroll.setInt(1, Integer.parseInt(accountnumber));
                recordenroll.execute();
                
                String querydelete = "delete from student where accountnumber=?";
                recorddelete = conn.prepareStatement(querydelete);
                recorddelete.setString(1, studentaccountnumber);
                recorddelete.execute();
                
                
                
                
                JOptionPane.showMessageDialog(this, "Student has been Pre Enrolled: Enroll Student to the enroll form");
                 accountnumber = null;
                txtfirstname.setText(null);
                txtmiddlename.setText(null);
                txtlastname.setText(null);
                cbgender.setSelectedIndex(0);
                txtage.setText(null);
                txtdateofbirth.setText(null);
                txtplaceofbirth.setText(null);
                txtaddress.setText(null);
                txtnameofguardian.setText(null);
                txtoccupation.setText(null);
                txtaddressofguardian.setText(null);
                txtstudentfatherfirstname.setText(null);
                txtstudentfathermiddlename.setText(null);
                txtstudentfatherlastname.setText(null);
                txtstudentmotherfirstname.setText(null);
                txtstudentmothermiddlename.setText(null);
                txtstudentmotherlastname.setText(null);
                txtreligion.setText(null);
                txttribe.setText(null);
                txtcitizenship.setText(null);
                txtelementary.setText(null);
                txtintermediate.setText(null);
                txtgrade7.setText(null);
                cbgrade7schoolyear.setSelectedIndex(0);
                txtgrade8.setText(null);
                cbgrade8schoolyear.setSelectedIndex(0);
                txtgrade9.setText(null);
                cbgrade9schoolyear.setSelectedIndex(0);
                txtgrade10.setText(null);
                cbgrade10schoolyear.setSelectedIndex(0);
                txtgrade11.setText(null);
                cbgrade11schoolyear.setSelectedIndex(0);
                txtgrade12.setText(null);
                cbgrade12schoolyear.setSelectedIndex(0);
                studentinformation();
           
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            } 
            }
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                accountnumber = null;
                txtfirstname.setText(null);
                txtmiddlename.setText(null);
                txtlastname.setText(null);
                cbgender.setSelectedIndex(0);
                txtage.setText(null);
                txtdateofbirth.setText(null);
                txtplaceofbirth.setText(null);
                txtaddress.setText(null);
                txtnameofguardian.setText(null);
                txtoccupation.setText(null);
                txtaddressofguardian.setText(null);
                txtstudentfatherfirstname.setText(null);
                txtstudentfathermiddlename.setText(null);
                txtstudentfatherlastname.setText(null);
                txtstudentmotherfirstname.setText(null);
                txtstudentmothermiddlename.setText(null);
                txtstudentmotherlastname.setText(null);
                txtreligion.setText(null);
                txttribe.setText(null);
                txtcitizenship.setText(null);
                txtelementary.setText(null);
                txtintermediate.setText(null);
                txtgrade7.setText(null);
                cbgrade7schoolyear.setSelectedIndex(0);
                txtgrade8.setText(null);
                cbgrade8schoolyear.setSelectedIndex(0);
                txtgrade9.setText(null);
                cbgrade9schoolyear.setSelectedIndex(0);
                txtgrade10.setText(null);
                cbgrade10schoolyear.setSelectedIndex(0);
                txtgrade11.setText(null);
                cbgrade11schoolyear.setSelectedIndex(0);
                txtgrade12.setText(null);
                cbgrade12schoolyear.setSelectedIndex(0);
                studentinformation();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbgrade10schoolyear;
    private javax.swing.JComboBox<String> cbgrade11schoolyear;
    private javax.swing.JComboBox<String> cbgrade12schoolyear;
    private javax.swing.JComboBox<String> cbgrade7schoolyear;
    private javax.swing.JComboBox<String> cbgrade8schoolyear;
    private javax.swing.JComboBox<String> cbgrade9schoolyear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable tblstudentinformation;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtaddressofguardian;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcitizenship;
    private javax.swing.JTextField txtdateofbirth;
    private javax.swing.JTextField txtelementary;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgrade10;
    private javax.swing.JTextField txtgrade11;
    private javax.swing.JTextField txtgrade12;
    private javax.swing.JTextField txtgrade7;
    private javax.swing.JTextField txtgrade8;
    private javax.swing.JTextField txtgrade9;
    private javax.swing.JTextField txtintermediate;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtmiddlename;
    private javax.swing.JTextField txtnameofguardian;
    private javax.swing.JTextField txtoccupation;
    private javax.swing.JTextField txtplaceofbirth;
    private javax.swing.JTextField txtreligion;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtstudentfatherfirstname;
    private javax.swing.JTextField txtstudentfatherlastname;
    private javax.swing.JTextField txtstudentfathermiddlename;
    private javax.swing.JTextField txtstudentmotherfirstname;
    private javax.swing.JTextField txtstudentmotherlastname;
    private javax.swing.JTextField txtstudentmothermiddlename;
    private javax.swing.JTextField txttribe;
    // End of variables declaration//GEN-END:variables
}
