/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informationSystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author castillo
 */
public class studentyearlevel extends javax.swing.JFrame {
    DBconnetion mycon = new DBconnetion();
    Connection conn;
    PreparedStatement pstmt;
    Statement stmt;
    ResultSet rs;
    String trackstrandlable;
    
    String categoryid;
    String yearlevelid;
    public studentyearlevel() {
        initComponents();
        mycon.doConnect();
        studentcategory();
        lblcategoryid.setText(null);
        lblyearlevelid.setText(null);
        center();
        trackstrand();
        yearleveltable();
    }
    
        void yearleveltable(){
            try {
                conn = mycon.con;
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT \n" +
"  yearlevel.yearlevelid, \n" +
"  yearlevel.yearlevelname, \n" +
"  category.categoryname, \n" +
"  yearlevel.trackstrandname\n" +
"FROM \n" +
"  public.category, \n" +
"  public.yearlevel\n" +
"WHERE \n" +
"  yearlevel.categoryid = category.categoryid");
            
            DefaultTableModel model = ((DefaultTableModel) tblyearlevel.getModel());
            model.getDataVector().removeAllElements();
            
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
    }
    
    void trackstrand(){
        try {
            conn = mycon.con;
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select * from studenttrackstrand");
            
            while(rs.next()){
                cbtrackstrand.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }
    
         void center(){

    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize() ;
    Dimension jscreen = this.getSize();

    this.setLocation((screen.width - jscreen.width)/2, ((screen.height-jscreen.height)/2)-90);

    } 
    
            public void close(){
    WindowEvent winclose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
}
            
            void studentcategory(){
                try {
                    conn = mycon.con;
                stmt = conn.createStatement();
                rs = stmt.executeQuery("select * from category");
                
                while(rs.next()){
                    cbcategory.addItem(rs.getString(2));
                }
                } catch (Exception e) {
                }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblcategoryid = new javax.swing.JLabel();
        lblyearlevelid = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtyyearlevelid = new javax.swing.JTextField();
        txtyearlevelname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbcategory = new javax.swing.JComboBox<>();
        cbtrackstrand = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblyearlevel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jInternalFrame1.setVisible(true);

        jPanel1.setLayout(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 440, 100);
        jPanel1.add(lblcategoryid);
        lblcategoryid.setBounds(0, 0, 0, 0);

        lblyearlevelid.setText("jLabel5");
        jPanel1.add(lblyearlevelid);
        lblyearlevelid.setBounds(0, 0, 34, 14);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setFocusCycleRoot(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonicons/Save-icon.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonicons/Delete-icon (1).png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonicons/Button-Refresh-icon.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonicons/Button-Close-icon.png"))); // NOI18N
        jButton5.setText("Back");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(0, 100, 440, 70);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Yearlevel ID");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Yearlevel Name");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Search");

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("Category");

        cbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(SET CATEGORY HERE)" }));
        cbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoryActionPerformed(evt);
            }
        });

        cbtrackstrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(SET TRACKSTRAND HERE)" }));
        cbtrackstrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtrackstrandActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("Track / Strand");

        tblyearlevel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Yearlevel ID", "Yearlevel Name", "Category Name", "Track / Strand"
            }
        ));
        tblyearlevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblyearlevelMouseClicked(evt);
            }
        });
        tblyearlevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblyearlevelKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblyearlevel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbtrackstrand, javax.swing.GroupLayout.Alignment.TRAILING, 0, 234, Short.MAX_VALUE)
                            .addComponent(cbcategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtyearlevelname)
                            .addComponent(txtyyearlevelid))
                        .addContainerGap())))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtyyearlevelid)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtyearlevelname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbcategory)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel4))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbtrackstrand, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsearch)
                        .addComponent(jButton4))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 170, 440, 370);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
              if(txtsearch.getText().isEmpty()){
            txtyyearlevelid.setText(null);
            txtyearlevelname.setText(null);
        }else{
                             try {
                conn = mycon.con;
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT \n" +
"  yearlevel.yearlevelid, \n" +
"  yearlevel.yearlevelname, \n" +
"  category.categoryname, \n" +
"  yearlevel.trackstrandname\n" +
"FROM \n" +
"  public.category, \n" +
"  public.yearlevel\n" +
"WHERE \n" +
"  category.categoryid = yearlevel.categoryid and yearlevelname like'" + txtsearch.getText().toUpperCase() + "%' or yearlevel.yearlevelid like'" + txtsearch.getText().toUpperCase() + "%'");
            
            DefaultTableModel model = ((DefaultTableModel) tblyearlevel.getModel());
            model.getDataVector().removeAllElements();
            
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
                txtyyearlevelid.setText(rs.getString(1));
                txtyearlevelname.setText(rs.getString(2));

                
                cbtrackstrand.setSelectedItem(rs.getString(4));
                yearlevelid = rs.getString(1);
                 cbcategory.setSelectedItem(rs.getString(3));
            }
          
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
        }
    }//GEN-LAST:event_txtsearchKeyReleased
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                         try {
                conn = mycon.con;
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT \n" +
"  yearlevel.yearlevelid, \n" +
"  yearlevel.yearlevelname, \n" +
"  category.categoryname, \n" +
"  yearlevel.trackstrandname\n" +
"FROM \n" +
"  public.category, \n" +
"  public.yearlevel\n" +
"WHERE \n" +
"  category.categoryid = yearlevel.categoryid and yearlevelname like'" + txtsearch.getText().toUpperCase() + "%' or yearlevel.yearlevelid like'" + txtsearch.getText().toUpperCase() + "%'");
            
            DefaultTableModel model = ((DefaultTableModel) tblyearlevel.getModel());
            model.getDataVector().removeAllElements();
            
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
                txtyyearlevelid.setText(rs.getString(1));
                txtyearlevelname.setText(rs.getString(2));

                
                cbtrackstrand.setSelectedItem(rs.getString(4));
                yearlevelid = rs.getString(1);
                 cbcategory.setSelectedItem(rs.getString(3));
            }
          
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcategoryActionPerformed

    private void cbtrackstrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtrackstrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtrackstrandActionPerformed

    private void tblyearlevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblyearlevelMouseClicked
        try {
            int yearlevelrow = tblyearlevel.getSelectedRow();
            
            String yearlevelrow1 = (tblyearlevel.getModel().getValueAt(yearlevelrow, 1).toString());
            
            String yearlevelquery = "SELECT \n" +
"  yearlevel.yearlevelid, \n" +
"  yearlevel.yearlevelname, \n" +
"  category.categoryname, \n" +
"  yearlevel.trackstrandname\n" +
"FROM \n" +
"  public.category, \n" +
"  public.yearlevel\n" +
"WHERE \n" +
"  category.categoryid = yearlevel.categoryid and yearlevelname='" + yearlevelrow1 + "'";
            
            pstmt = conn.prepareStatement(yearlevelquery);
            rs = pstmt.executeQuery();
            
            if(rs.next()){
                txtyyearlevelid.setText(rs.getString(1));
                txtyearlevelname.setText(rs.getString(2));
                String categoryname =rs.getString(3);
                cbcategory.setSelectedItem(categoryname);
                String trackstrand = rs.getString(4);
                cbtrackstrand.setSelectedItem(trackstrand);
                yearlevelid = rs.getString(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_tblyearlevelMouseClicked

    private void tblyearlevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblyearlevelKeyReleased
        // TODO 
    }//GEN-LAST:event_tblyearlevelKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        studentform student = new studentform();
        student.setVisible(true);
        close();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int askupdate = JOptionPane.showConfirmDialog(this, "Do you want to update this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(askupdate == JOptionPane.YES_OPTION){
            try {
                conn = mycon.con;
                String updatequery = "update yearlevel set yearlevelid=?, yearlevelname=?, categoryid=?, trackstrandname=? where yearlevelid=?";
                stmt = conn.createStatement();
                rs = stmt.executeQuery("select * from category where categoryname like'" + cbcategory.getSelectedItem().toString() + "'");
                
                while(rs.next()){
                    categoryid = rs.getString(1);
                }
                pstmt = conn.prepareStatement(updatequery);
                pstmt.setString(1, txtyyearlevelid.getText().toUpperCase());
                pstmt.setString(2, txtyearlevelname.getText().toUpperCase());
                pstmt.setString(3, categoryid);
                pstmt.setString(4, cbtrackstrand.getSelectedItem().toString());
                pstmt.setString(5, yearlevelid);
                pstmt.execute();


                yearleveltable();
                JOptionPane.showMessageDialog(this, "Data has been updated");
                txtyearlevelname.setText(null);
                txtyyearlevelid.setText(null);
                cbcategory.setSelectedIndex(0);
                cbtrackstrand.setSelectedIndex(0);
                txtsearch.setText(null);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement sectiondelte;
        int askdelete = JOptionPane.showConfirmDialog(this, "Do you want to delete this data?" , "Messsage", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        try {

            if(askdelete == JOptionPane.YES_OPTION){
                if(txtyyearlevelid.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Please select the data first");
                }else{
                    conn = mycon.con;
                String querydelete = "delete from yearlevel where yearlevelid=?";
                pstmt = conn.prepareStatement(querydelete);
                pstmt.setString(1, txtyyearlevelid.getText().toUpperCase());
                pstmt.execute();

                String deletesection = "delete from section where yearlevelid=?";
                sectiondelte = conn.prepareStatement(deletesection);
                sectiondelte.setString(1, yearlevelid);
                sectiondelte.execute();
                
                PreparedStatement subject;
                String subjectdelete = "delete from subject where yearlevelid=?";
                subject = conn.prepareStatement(subjectdelete);
                subject.setString(1, txtyyearlevelid.getText().toUpperCase());
                subject.execute();
                
                JOptionPane.showMessageDialog(this, "Data has been deleted");

                txtyyearlevelid.setText(null);
                txtyearlevelname.setText(null);
                txtsearch.setText(null);
                yearleveltable();
                }
                

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int ask = JOptionPane.showConfirmDialog(this, "Do you want to save this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(ask == JOptionPane.YES_OPTION){

            try {
                conn = mycon.con;
                stmt = conn.createStatement();
                String yearlevel;
                rs = stmt.executeQuery("select categoryid from category where categoryname like'" + cbcategory.getSelectedItem().toString().toUpperCase() + "%'");

                if(rs.next()){
                    lblcategoryid.setText(rs.getString(1));
                }

                String querysave = "insert into yearlevel values(?,?,?,?)";
                pstmt = conn.prepareStatement(querysave);
                pstmt.setString(1, txtyyearlevelid.getText().toUpperCase());
                pstmt.setString(2, txtyearlevelname.getText().toUpperCase());
                pstmt.setString(3, lblcategoryid.getText().toUpperCase());
                pstmt.setString(4, cbtrackstrand.getSelectedItem().toString().toUpperCase());
                pstmt.execute();

                JOptionPane.showMessageDialog(this, "Data saved");
                txtyyearlevelid.setText(null);
                txtyearlevelname.setText(null);
                lblcategoryid.setText(null);
                txtsearch.setText(null);
                cbcategory.setSelectedIndex(0);
                cbtrackstrand.setSelectedIndex(0);
                yearleveltable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcategory;
    private javax.swing.JComboBox<String> cbtrackstrand;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblcategoryid;
    private javax.swing.JLabel lblyearlevelid;
    private javax.swing.JTable tblyearlevel;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtyearlevelname;
    private javax.swing.JTextField txtyyearlevelid;
    // End of variables declaration//GEN-END:variables
}
