/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informationSystem;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author castillo
 */
public class trackstrand extends javax.swing.JFrame {
    DBconnetion mycon =  new DBconnetion();
    Connection conn;
    PreparedStatement pstmt;
    Statement stmt;
    ResultSet rs;
    String update;
    public trackstrand() {
        initComponents();
        mycon.doConnect();
        trackstrand();
    }
                 public void close(){
    WindowEvent winclose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
}
                 void trackstrand(){
                     try {
                         conn = mycon.con;
                         stmt = conn.createStatement();
                         rs = stmt.executeQuery("select * from studenttrackstrand");
                         
                         DefaultTableModel model = ((DefaultTableModel) tbltrackstrand.getModel());
                         model.getDataVector().removeAllElements();
                         
                         while(rs.next()){
                             model.addRow(new Object[]{rs.getString(1)});
                         }
                     } catch (Exception e) {
                     }
                 }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltrackstrand = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txttrackstrand1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 200, 70, 24);

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch);
        txtsearch.setBounds(80, 200, 250, 30);

        tbltrackstrand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Track / Strand"
            }
        ));
        tbltrackstrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltrackstrandMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltrackstrand);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 240, 430, 90);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Student Track or Strand");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 20, 220, 24);
        jPanel1.add(txttrackstrand1);
        txttrackstrand1.setBounds(70, 150, 300, 30);

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(340, 200, 73, 30);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton4.setText("Delete");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setText("Update");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton6.setText("Show all data");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(10, 50, 430, 70);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int asksave = JOptionPane.showConfirmDialog(this, "Do you want to save this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(asksave == JOptionPane.YES_OPTION){
            try {
                conn = mycon.con;
                String query = "insert into studenttrackstrand values(?)";
                pstmt = conn.prepareStatement(query);
                pstmt.setString(1, txttrackstrand1.getText().toUpperCase());
                pstmt.execute();
                
                JOptionPane.showMessageDialog(this, "Data has been saved");
                trackstrand();
                txttrackstrand1.setText(null);
                txtsearch.setText(null);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       settings studentsettings = new settings();
       studentsettings.setVisible(true);
       close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int askdelete = JOptionPane.showConfirmDialog(this, "Do you want to delete this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(askdelete == JOptionPane.YES_OPTION){
            try {
                conn = mycon.con;
            String deletequery = "delete from studenttrackstrand where trackstrandname=?";
            pstmt = conn.prepareStatement(deletequery);
            pstmt.setString(1, txttrackstrand1.getText().toUpperCase());
            pstmt.execute();
            
            JOptionPane.showMessageDialog(this, "Data has been deleted");
            trackstrand();
            txtsearch.setText(null);
            txttrackstrand1.setText(null);
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        if(txtsearch.getText().isEmpty()){
            txttrackstrand1.setText(null);
        }else{
            try {
               conn = mycon.con;
               stmt = conn.createStatement();
               rs= stmt.executeQuery("select * from studenttrackstrand where trackstrandname like'" + txtsearch.getText().toUpperCase() + "%'");
               
               DefaultTableModel model = ((DefaultTableModel) tbltrackstrand.getModel());
                         model.getDataVector().removeAllElements();
                         
                         while(rs.next()){
                             model.addRow(new Object[]{rs.getString(1)});
                             txttrackstrand1.setText(rs.getString(1));
                             update = rs.getString(1);
                         }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
               conn = mycon.con;
               stmt = conn.createStatement();
               rs= stmt.executeQuery("select * from studenttrackstrand where trackstrandname like'" + txtsearch.getText().toUpperCase() + "%'");
               
               DefaultTableModel model = ((DefaultTableModel) tbltrackstrand.getModel());
                         model.getDataVector().removeAllElements();
                         
                         while(rs.next()){
                             model.addRow(new Object[]{rs.getString(1)});
                             txttrackstrand1.setText(rs.getString(1));
                             update = rs.getString(1);
                         }
            } catch (Exception e) {
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int askupdate = JOptionPane.showConfirmDialog(this, "Do you want to update this data?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(askupdate == JOptionPane.YES_OPTION){
            try {
                conn = mycon.con;
              
                
                
                   
                    String updatequery = "update studenttrackstrand set trackstrandname=? where trackstrandname=?";
                pstmt = conn.prepareStatement(updatequery);
                pstmt.setString(1, txttrackstrand1.getText().toUpperCase());
                pstmt.setString(2, update.toUpperCase());
                pstmt.execute();
                
                JOptionPane.showMessageDialog(this, "Data has been updated");
                
                
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbltrackstrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltrackstrandMouseClicked
        try {
             int trackstrandrow = tbltrackstrand.getSelectedRow();
        String trackstrandrow1 = (tbltrackstrand.getModel().getValueAt(trackstrandrow, 0).toString());
        
        String trackstrandtable = "select * from studenttrackstrand where trackstrandname='" + trackstrandrow1 + "'";
        pstmt = conn.prepareStatement(trackstrandtable);
        rs = pstmt.executeQuery();
        
        if(rs.next()){
            txttrackstrand1.setText(rs.getString(1));
            update = rs.getString(1);
        }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_tbltrackstrandMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        trackstrand();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trackstrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trackstrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trackstrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trackstrand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trackstrand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbltrackstrand;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttrackstrand1;
    // End of variables declaration//GEN-END:variables
}
